Updates

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,8 +1,11 @@
 FROM mcr.microsoft.com/vscode/devcontainers/dotnet:6.0-focal
 
+# Make sure pipe failures trigger build failures
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
 # Install native components
 RUN apt-get update && \
-    apt-get install -y \
+    apt-get install -y --no-install-recommends \
         curl \
         dos2unix \
         git \
@@ -10,7 +13,10 @@ RUN apt-get update && \
         sudo \
         zsh \
         zsh-syntax-highlighting \
-        zsh-autosuggestions
+        zsh-autosuggestions \
+    && \
+    apt-get clean && \
+    rm -rf /var/lib/apt/lists/*
 
 # Switch to non-root user
 USER vscode
@@ -18,19 +24,17 @@ USER vscode
 # Select oh my zsh plugins
 # Install 'bat' from GitHub release drop
 # Install 'exa' from GitHub release drop
+WORKDIR /tmp/work
 RUN sed -i "s/^plugins=.*/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/" ~/.zshrc && \
     \
-    mkdir -p /tmp/work && \
-    cd /tmp/work && \
-    \
-    wget https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-musl_0.22.1_amd64.deb -O ./bat.deb && \
+    curl https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-musl_0.22.1_amd64.deb --output ./bat.deb && \
     sudo dpkg -i ./bat.deb && \
     sudo apt-get install -f && \
     \
-    wget https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip -O ./exa.zip && \
+    curl https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip --output ./exa.zip && \
     unzip ./exa.zip && \
     sudo mv ./bin/* /usr/bin && \
     sudo mv ./completions/exa.zsh /usr/share/zsh/vendor-completions/_exa && \
     \
-    cd && \
-    rm -rf /tmp/work
+    curl https://get.trunk.io -fsSL | sudo bash -s - -y && \
+    sudo chmod a+r /usr/local/bin/trunk
